name: gpt4o

backend:
  type: openai_gpt4o
  model_name: gpt-4o
  api_key_env: OPENAI_API_KEY
  batch_size: 1

generation:
  max_new_tokens: 220
  repetition_penalty: 1.0
  do_sample: false
  temperature: 0.0
  top_p: 1.0

prompt:
  use_examples: false
  use_reasoning: true
  include_bbox_json: true

