name: llava_onevision

backend:
  type: llava_hf
  model_name: llava-hf/llava-onevision-qwen2-7b-ov-hf
  batch_size: 1
  use_4bit: true
  compile_model: false
  device_map: auto
  trust_remote_code: true

generation:
  max_new_tokens: 220
  repetition_penalty: 1.1
  do_sample: false
  temperature: 0.2
  top_p: 0.9
  top_k: 40

prompt:
  use_examples: false
  use_reasoning: true
  include_bbox_json: true

